receivers:
  otlp:
    protocols:
      grpc:  # port 4317

processors:
  batch:

exporters:
  debug:
    verbosity: detailed   # every metric datapoint & span

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
