[package]
name        = "gst_otel_tracer"
version     = "0.1.0"
edition     = "2021"

[lib]
crate-type  = ["cdylib"]

[dependencies]
# ── GStreamer stack ───────────────────────────────────────────────
glib              = "0.18"
gstreamer         = { version = "0.23.6", features = ["v1_24"] }
gstreamer-sys     = "0.23.6"  # raw FFI for hook registration

once_cell         = "1.19"
fastrand          = "2.0"

opentelemetry           = { version = "0.22", features = ["metrics"] }
opentelemetry_sdk       = { version = "0.22", features = ["metrics"] }
opentelemetry-otlp      = { version = "0.15", features = ["tonic", "metrics", "trace"] }
tokio                   = { version = "1",   features = ["rt-multi-thread", "macros"] }
