[package]
name        = "gst_prometheus_latency_tracer"
version     = "0.1.0"
edition     = "2021"

[lib]
name = "gsttelemetytracer"
crate-type  = ["cdylib", "rlib"]

[profile.test]
debug = true
strip = false
split-debuginfo = "off"

[dependencies]
# ── GStreamer stack ───────────────────────────────────────────────
glib = "0.20"
gobject-sys = "0.20"
gstreamer         = { version = "0.23", features = ["v1_16"] }
gstreamer-sys     = "0.23"  # raw FFI for hook registration
lazy_static = "1.4"
prometheus =  "0.14"
tiny_http = "0.12"
dashmap = "6.1"
once_cell = "1.19"

[dev-dependencies]
reqwest = { version = "0.12", features = ["blocking"] }

[features]
noop = []
