[package]
name        = "gst_prometheus_latency_tracer"
version     = "0.1.0"
edition     = "2021"

[lib]
name = "gsttelemetytracer"
crate-type  = ["cdylib", "rlib"]

[profile.test]
inherits = "release"
debug = true

[dependencies]
# ── GStreamer stack ───────────────────────────────────────────────
glib = "0.20"
gobject-sys = "0.20"
gstreamer         = { version = "0.23.6", features = ["v1_16"] }
gstreamer-sys     = "0.23.6"  # raw FFI for hook registration
lazy_static = "1.4.0"
prometheus =  "0.14.0"
tiny_http = "0.12.0"
dashmap = "6.1.0"
once_cell = "1.19.0"

[dev-dependencies]
reqwest = { version = "0.12", features = ["blocking"] }

[features]
noop = []
