[package]
name        = "gst-noop-tracer"
version     = "0.1.0"
edition     = "2021"

[lib]
name = "gstnooptracer"
crate-type  = ["cdylib", "rlib"]

[dependencies]
glib.workspace=true
gobject-sys.workspace=true
gstreamer.workspace=true       
gstreamer-sys.workspace=true   

[features]
noop = []
