name: Security Audit

on:
  push:
    branches: [main]
  pull_request:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
      - uses: extractions/setup-just@v3
        with:
          just-version: 1.40.0
      - name: Run audit
        run: just audit
      - name: Run fmt check
        run: just fmt-check
      - name: Run clippy
        run: just lint
      - name: Run coverage
        run: just coverage
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: tarpaulin-report.html
