name: Security Audit

on:
  push:
    branches: [main]
  pull_request:

jobs:
  audit:
    runs-on: ubuntu-latest
    container: ghcr.io/lrwm3/gst-tracer-otel-ci:latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache Cargo registry
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-

      - name: Cache Cargo build
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-cargo-target-${{ hashFiles('**/Cargo.lock') }}-release
          restore-keys: |
            ${{ runner.os }}-cargo-target-

      - name: Run audit
        run: just audit
      - name: Run lint
        run: just lint
      - name: Run coverage
        run: just coverage
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: tarpaulin-report.html
      - name: Commit formatted code
        if: github.event_name == 'pull_request' && github.event.pull_request.state == 'open' && github.event.pull_request.draft == false
        run: |
          if ! git diff --quiet; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git commit -am "fix(tracer): format code"
            git push
          fi
